//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "account_group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_uuid: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub group_uuid: Uuid,
    pub last_known: Option<DateTimeUtc>,
    #[sea_orm(
        belongs_to,
        from = "account_uuid",
        to = "uuid",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    pub accounts: HasOne<super::accounts::Entity>,
    #[sea_orm(
        belongs_to,
        from = "group_uuid",
        to = "uuid",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    pub groups: HasOne<super::groups::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
