//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub user_name: String,
    #[sea_orm(unique)]
    pub account: String,
    #[sea_orm(has_many)]
    pub messages: HasMany<super::messages::Entity>,
    #[sea_orm(has_many, via = "account_group")]
    pub groups: HasMany<super::groups::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
