//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub content: String,
    pub account_uuid: Uuid,
    pub group_uuid: Uuid,
    pub create_at: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "account_uuid",
        to = "uuid",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    pub accounts: HasOne<super::accounts::Entity>,
    #[sea_orm(
        belongs_to,
        from = "group_uuid",
        to = "uuid",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    pub groups: HasOne<super::groups::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
