//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "auths")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub token: Uuid,
    pub account: Uuid,
    pub create_at: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "account",
        to = "uuid",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    pub accounts: HasOne<super::accounts::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
